#ATIVIDADE PARA CASA
#ELABORE UM ALGORITMO USANDO OPERAÇÕES PARA INFORMAR SE UMA PESSOA É OBRIGADA A VOTAR.
#CONSIDERE QUE A REGRA É QUE MENORES E MAIORES QUE 65 NÃO SÃO OBRIGADOS A VOTAR.

import os
os.system ("clear")

# ENTRADA
idade int(input("Digite sua idade: "))

# PROCESSAMENTO
# OPÇÃO 1.
# IF IDADE < 18 OR 





